# authendication credintials
credentials:
  usernames:
    emon:
      email: emon@gmail.com
      name: Injamam
      password: $2b$12$tQnNvyRRGOdoTP9ulOLsGujok7/aam31D16gySoMYFpBCIk939XPi # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - kalim@growwithdata.net



db:
  host: "localhost"
  user: "root"
  passwd: "abc"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "hoque.chy.08@gmail.com"
  pass: 'abc'